server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: management-service
          uri: http://localhost:9002/management-service
          predicates:
            - Path=/v1/management/**
          filters:
            - RewritePath=/v1/management/(?<path>.*), /$\{path}
        - id: shopping-service
          uri: http://localhost:9001/shopping-service
          predicates:
            - Path=/v1/shopping/**
          filters:
            - RewritePath=/v1/shopping/(?<path>.*), /$\{path}
      #        - id: order-service
      #          uri: http://localhost:9003/
      #          predicates:
      #            - Path=/api/v1/order/**

      #        - id: inventory-service
      #          uri: http://localhost:9004/
      #          predicates:
      #            - Path=/api/v1/inventory/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
