server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: management-service
          uri: lb://management-service
          predicates:
            - Path=/v1/management/**
          filters:
            - RewritePath=/v1/management/(?<path>.*), /$\{path}
        - id: shopping-service
          uri: http://localhost:9001/shopping-service
          predicates:
            - Path=/v1/shopping/**
          filters:
            - RewritePath=/v1/shopping/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/order/**
          filters:
            - RewritePath=/v1/order/(?<path>.*), /$\{path}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

---
eureka: #<1>
  instance:
    app-name: ${HOSTNAME:gateway-service}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

---
eureka:
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    hostname: ${HOSTNAME:gateway-service}
